version: '3'

services:
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongo:/data/db
        env_file:
          - .env
        command: --replSet rs0

    web_app:
        build:
            dockerfile: Dockerfile
            context: .
        env_file:
            - .env
        depends_on:
            - mongo
        ports:
            - "8000:8000"

    mongoclient:
        image: mongo
        depends_on:
            - mongo
        volumes:
            - ./dev_scripts:/dev_scripts
        entrypoint:
            - /dev_scripts/initiate_replica.sh
